# Generated by Django 5.1.3 on 2024-12-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdiagApp', '0008_rename_slotid_payment_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
