# Generated by Django 4.2.2 on 2023-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0007_birth_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('dod', models.DateField()),
                ('deathplace', models.CharField(max_length=255)),
                ('death', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('identification', models.CharField(max_length=255)),
                ('idproof', models.FileField(null=True, upload_to='uploadfiles')),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
            ],
        ),
    ]
