# Generated by Django 4.2.2 on 2023-07-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0008_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.registration'),
        ),
    ]
