# Generated by Django 4.2.2 on 2023-07-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0009_death_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridename', models.CharField(max_length=255)),
                ('bridefather', models.CharField(max_length=255)),
                ('bridemother', models.CharField(max_length=255)),
                ('bridedob', models.DateField()),
                ('brideaddress', models.CharField(max_length=300)),
                ('groomname', models.CharField(max_length=255)),
                ('groomfather', models.CharField(max_length=255)),
                ('groommother', models.CharField(max_length=255)),
                ('groomdob', models.DateField()),
                ('groomaddress', models.CharField(max_length=300)),
                ('marriagedate', models.DateField()),
                ('marriageplace', models.CharField(max_length=255)),
                ('marriagetype', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('idproofbride', models.FileField(null=True, upload_to='uploadfiles')),
                ('idproofgroom', models.FileField(null=True, upload_to='uploadfiles')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.registration')),
            ],
        ),
    ]
