# Generated by Django 4.2.2 on 2023-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0014_birth_date_death_date_license_date_marriage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='photo',
            field=models.FileField(null=True, upload_to='uploadimages'),
        ),
    ]
