# Generated by Django 4.2.2 on 2023-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0018_birth_certificate_death_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='martial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voters',
            name='martial',
            field=models.CharField(max_length=100),
        ),
    ]
