# Generated by Django 5.1.6 on 2026-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0019_alter_passport_martial_alter_voters_martial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='child_blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='father_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='father_blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='father_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='father_idproof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='birth',
            name='father_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='birth',
            name='mother_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='mother_blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='mother_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='mother_idproof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='birth',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
