# Generated by Django 4.2.15 on 2026-04-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0020_birth_child_blood_birth_father_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='father_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='father_blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='father_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='father_idproof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='death',
            name='father_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='death',
            name='mother_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='mother_blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='mother_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='mother_idproof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='death',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
