# Generated by Django 4.2.15 on 2026-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0021_death_father_address_death_father_blood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='father_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='father_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='father_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='father_proof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='passport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passport',
            name='mother_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='mother_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='mother_proof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='passport',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
