# Generated by Django 4.2.15 on 2026-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0022_passport_father_address_passport_father_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='father_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='father_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='father_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='father_proof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='voters',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voters',
            name='mother_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='mother_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='mother_proof',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='voters',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
