# Generated by Django 4.2.15 on 2026-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0024_license_father_address_license_father_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marriage',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
