# Generated by Django 5.1.6 on 2026-04-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0025_marriage_is_verified_marriage_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='certificate',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
    ]
