# Generated by Django 5.1.6 on 2026-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0027_passport_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploadfiles'),
        ),
    ]
