# Generated by Django 4.0.4 on 2022-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialregister',
            old_name='cnfpass',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='socialregister',
            name='dob',
        ),
        migrations.AddField(
            model_name='socialregister',
            name='phone',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialregister',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
