# Generated by Django 4.0.4 on 2022-10-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0002_rename_cnfpass_socialregister_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialregister',
            name='password',
        ),
    ]
