# Generated by Django 4.0.4 on 2022-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0003_remove_socialregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialregister',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
