# Generated by Django 4.0.4 on 2022-10-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0005_authreg_userreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='authreg',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterapp.login'),
        ),
        migrations.AddField(
            model_name='socialregister',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterapp.login'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterapp.login'),
        ),
    ]
