# Generated by Django 4.0.4 on 2022-10-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0006_authreg_loginid_socialregister_loginid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=100, null=True)),
                ('amount', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRegUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=100, null=True)),
                ('amount', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
