# Generated by Django 4.0.4 on 2022-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0007_donationcommon_donationregusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcommon',
            name='cardno',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationcommon',
            name='cvv',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationcommon',
            name='mm',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationcommon',
            name='yy',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationregusers',
            name='cardno',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationregusers',
            name='cvv',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationregusers',
            name='mm',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationregusers',
            name='yy',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
