# Generated by Django 4.0.4 on 2022-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0008_donationcommon_cardno_donationcommon_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationregusers',
            name='uid',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
