# Generated by Django 4.0.4 on 2022-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0010_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reply',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
