# Generated by Django 4.0.4 on 2022-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0012_messages_status_alter_messages_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='reply',
        ),
    ]
