# Generated by Django 4.0.4 on 2022-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0013_remove_messages_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reply',
            field=models.CharField(default='Awaiting Response', max_length=100, null=True),
        ),
    ]
