# Generated by Django 4.0.4 on 2022-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0015_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, null=True)),
                ('disaster', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('des', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
