# Generated by Django 4.0.4 on 2022-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0016_disaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='samount',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
