# Generated by Django 4.0.4 on 2022-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0018_officerreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officerid', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('members', models.IntegerField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
