# Generated by Django 4.0.4 on 2022-10-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0020_campmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officerid', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=100, null=True)),
                ('campid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterapp.campreg')),
            ],
        ),
    ]
