# Generated by Django 4.0.4 on 2022-10-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0021_camprequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('status', models.CharField(default='raised', max_length=100, null=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterapp.userreg')),
            ],
        ),
    ]
