# Generated by Django 4.0.4 on 2022-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0022_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=100, null=True)),
                ('campid', models.IntegerField(max_length=100, null=True)),
                ('itemname', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
