# Generated by Django 4.0.4 on 2022-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0023_userdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='No Reply', max_length=100, null=True),
        ),
    ]
