# Generated by Django 4.0.6 on 2022-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0025_rescueteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueteam',
            name='uid',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
