# Generated by Django 4.0.6 on 2022-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0026_rescueteam_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
