# Generated by Django 4.0.6 on 2022-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0027_disaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disaster',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
