# Generated by Django 4.0.4 on 2022-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0028_disaster_district_disaster_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='image',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
