# Generated by Django 4.0.4 on 2022-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0029_claims_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
