# Generated by Django 4.0.4 on 2022-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0030_alter_claims_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
