# Generated by Django 4.0.4 on 2022-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0031_disaster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claims',
            name='holdername',
        ),
        migrations.AddField(
            model_name='claims',
            name='aadhaar',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
