# Generated by Django 4.0.4 on 2022-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0032_remove_claims_holdername_claims_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='campreg',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
