# Generated by Django 5.1.6 on 2025-02-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='expert',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
