# Generated by Django 5.1.6 on 2025-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_file_expert_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='expertise',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
