# Generated by Django 5.1.6 on 2025-02-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_expert_experience_expert_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='file')),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
