# Generated by Django 5.0.7 on 2025-02-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='file')),
                ('skintone', models.CharField(choices=[('fair', 'Fair'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=50, null=True)),
                ('skintone_image', models.ImageField(blank=True, null=True, upload_to='skintone_images/')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
