# Generated by Django 5.0.7 on 2025-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
