# Generated by Django 5.0.7 on 2025-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_scheduled_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
