# Generated by Django 5.0.7 on 2025-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_booking_scheduled_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
