# Generated by Django 5.0.7 on 2025-02-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_booking_time_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='scheduled_datetime',
            new_name='scheduled_date',
        ),
    ]
