# Generated by Django 5.0.7 on 2025-02-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_scheduled_datetime_booking_scheduled_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
