# Generated by Django 5.0.7 on 2025-02-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='file',
        ),
    ]
