# Generated by Django 5.0.7 on 2025-02-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_skin_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='file')),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
