# Generated by Django 5.0.7 on 2025-02-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_chat_delete_homebookings_delete_homeservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='customer_id',
            new_name='customerid',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='expert_id',
            new_name='sellerid',
        ),
    ]
