# Generated by Django 5.0.7 on 2025-02-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_customer_id_chat_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.expert'),
        ),
    ]
