# Generated by Django 5.1.4 on 2026-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
