# Generated by Django 5.1.4 on 2026-01-07 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0005_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_modificatrion_app.employee'),
        ),
    ]
