# Generated by Django 5.1.4 on 2026-01-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0009_servicebooking_estimate_time_servicebooking_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='estimate_time',
        ),
    ]
