# Generated by Django 5.1.4 on 2026-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0010_remove_servicebooking_estimate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='estimate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
