# Generated by Django 5.1.4 on 2026-01-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0011_servicebooking_estimate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePartBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_modificatrion_app.employee')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_modificatrion_app.part')),
            ],
        ),
    ]
