# Generated by Django 5.1.4 on 2026-01-07 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0004_service_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_modificatrion_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_modificatrion_app.user')),
            ],
        ),
    ]
