# Generated by Django 5.1.4 on 2026-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_modificatrion_app', '0008_partbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='estimate_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
