# Generated by Django 5.1.4 on 2024-12-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_constructor_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constructor',
        ),
    ]
