# Generated by Django 5.1.4 on 2024-12-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_worker_experience_worker_job_type_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='worker',
        ),
    ]
