# Generated by Django 5.1.4 on 2024-12-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_request_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
