# Generated by Django 5.1.4 on 2024-12-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
    ]
