# Generated by Django 5.1.4 on 2024-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_request_worker_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='plot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
