# Generated by Django 5.1.4 on 2024-12-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_assignedworker_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedworker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='assignedworker',
            name='user_to_contractor_status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
    ]
