# Generated by Django 5.1.4 on 2024-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_assignedworker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contractor_to_worker_payment',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_status',
            field=models.CharField(default='NOT PAID', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='user_to_contractor_payment',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
