# Generated by Django 5.1.4 on 2024-12-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_request_contractor_to_worker_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
