# Generated by Django 5.1.4 on 2024-12-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_request_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedworker',
            name='user_to_contractor_status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='assignedworker',
            name='contractor_status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedworker',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
