# Generated by Django 5.1.4 on 2025-01-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedworker',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.request'),
        ),
    ]
