# Generated by Django 5.1.4 on 2025-03-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_assignedworker_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='usertype',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
    ]
