# Generated by Django 5.1.4 on 2025-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_feedback_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, null=True),
        ),
    ]
