# Generated by Django 5.1.4 on 2025-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_contractor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedworker',
            name='workeramt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
