# Generated by Django 5.1.4 on 2025-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_assignedworker_workeramt'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='worker_change_requested',
            field=models.BooleanField(default=False),
        ),
    ]
