# Generated by Django 5.1.4 on 2025-03-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
