# Generated by Django 5.1.4 on 2025-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_Read',
            field=models.BooleanField(default=False),
        ),
    ]
