# Generated by Django 5.1.4 on 2025-04-11 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_chat_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='customerid',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sellerid',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='time',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='utype',
        ),
        migrations.AddField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='userType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(),
        ),
    ]
