# Generated by Django 5.0.7 on 2025-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_customerid_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_Read',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
