# Generated by Django 5.0.7 on 2025-04-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_chat_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_Read',
        ),
    ]
