# Generated by Django 5.0.7 on 2025-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_Read',
            field=models.BooleanField(default=False),
        ),
    ]
