# Generated by Django 5.0.7 on 2025-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_chat_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_Read',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
