# Generated by Django 5.1.6 on 2026-03-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_chat_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='worker',
        ),
    ]
