# Generated by Django 5.1.6 on 2026-03-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_request_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.assignedworker')),
            ],
        ),
    ]
