# Generated by Django 5.1.6 on 2026-03-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.request'),
        ),
    ]
