# Generated by Django 5.1.6 on 2026-03-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_feedback_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.worker'),
        ),
    ]
