# Generated by Django 4.2.2 on 2023-07-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0004_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
