# Generated by Django 4.2.2 on 2023-07-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0005_alter_birth_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='phone',
            new_name='relation',
        ),
    ]
