# Generated by Django 4.2.2 on 2023-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0006_rename_phone_birth_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
