# Generated by Django 4.2.2 on 2023-07-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0010_marriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=255)),
                ('blood', models.CharField(max_length=10)),
                ('klno', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('identification', models.CharField(max_length=20)),
                ('idproof', models.FileField(null=True, upload_to='uploadfiles')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.registration')),
            ],
        ),
    ]
