# Generated by Django 4.2.2 on 2023-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='voters',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
