# Generated by Django 4.2.2 on 2023-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0015_license_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addauthority',
            name='taluk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='taluk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='taluk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='taluk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
