# Generated by Django 4.2.2 on 2023-08-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0016_addauthority_taluk_birth_taluk_death_taluk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.birth')),
                ('death', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.death')),
                ('marriage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.marriage')),
                ('registrar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='civilapp.addauthority')),
            ],
        ),
    ]
