# Generated by Django 4.2.2 on 2023-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilapp', '0017_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='certificate',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='death',
            name='certificate',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='certificate',
            field=models.FileField(null=True, upload_to='uploadfiles'),
        ),
    ]
