# Generated by Django 5.0.7 on 2025-03-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_deliveryagent_user_remove_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exporter',
        ),
    ]
