# Generated by Django 5.0.7 on 2025-03-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_exporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.servicerequest'),
        ),
    ]
