# Generated by Django 5.2.5 on 2025-08-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
