# Generated by Django 5.2.5 on 2025-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_student_batch_student_profile_picture_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
    ]
