# Generated by Django 5.2.5 on 2025-08-14 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_student_assigned_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('time_slot', models.CharField(choices=[('10-11', '10-11 AM'), ('11-12', '11-12 AM'), ('2-3', '2-3 PM')], default='10-11', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.teacher')),
            ],
            options={
                'unique_together': {('student', 'date', 'time_slot')},
            },
        ),
    ]
