# Generated by Django 5.1.6 on 2025-02-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0003_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
