# Generated by Django 5.1.6 on 2025-02-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
