# Generated by Django 5.1.6 on 2025-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
