# Generated by Django 5.1.6 on 2025-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0010_timeschedule_date_alter_timeschedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
