# Generated by Django 5.1.6 on 2025-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0011_alter_timeschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled')], default='Pending', max_length=20),
        ),
    ]
