# Generated by Django 5.1.6 on 2025-02-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0013_appointment_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='lab',
            new_name='assigned_lab',
        ),
    ]
