# Generated by Django 5.1.6 on 2025-02-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0014_rename_lab_appointment_assigned_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Crown', 'Crown'), ('Bridge', 'Bridge'), ('Denture', 'Denture'), ('Braces', 'Braces'), ('Retainer', 'Retainer'), ('Teeth Whitening', 'Teeth Whitening'), ('Implant', 'Implant'), ('Other', 'Other')], max_length=50)),
                ('order_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_app.appointment')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_app.dentist')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_app.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_app.patient')),
            ],
        ),
    ]
