# Generated by Django 5.1.6 on 2025-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0015_remove_appointment_created_at_laborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='delivery_status',
            field=models.CharField(choices=[('Not Delivered', 'Not Delivered'), ('Delivered to Dentist', 'Delivered to Dentist'), ('Delivered to Patient', 'Delivered to Patient')], default='Not Delivered', max_length=20),
        ),
    ]
