# Generated by Django 5.1.6 on 2025-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0016_laborder_delivered_date_laborder_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
