# Generated by Django 5.1.6 on 2025-02-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0017_timeschedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
