# Generated by Django 5.1.6 on 2025-02-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0018_laborder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Crown', 'Crown'), ('Bridge', 'Bridge'), ('Denture', 'Denture'), ('Braces', 'Braces'), ('Retainer', 'Retainer'), ('Teeth Whitening', 'Teeth Whitening'), ('Implant', 'Implant'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_app.lab')),
            ],
        ),
    ]
