# Generated by Django 5.1.6 on 2025-02-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0019_laborderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborder',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='laborder',
            name='order_details',
        ),
    ]
