# Generated by Django 5.1.6 on 2025-02-26 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0022_remove_review_comment_remove_review_dentist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_app.dentist'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_app.patient'),
        ),
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_app.appointment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
    ]
