# Generated by Django 5.1.6 on 2025-02-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0023_remove_review_review_text_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20),
        ),
    ]
