# Generated by Django 5.1.6 on 2025-03-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0024_alter_laborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='experience',
            field=models.FileField(null=True, upload_to='Experience'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='licences',
            field=models.FileField(null=True, upload_to='Licenses'),
        ),
    ]
