# Generated by Django 5.1.6 on 2025-03-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0025_dentist_experience_dentist_licences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='licences',
            new_name='licenses',
        ),
    ]
