# Generated by Django 5.1.6 on 2025-03-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0026_rename_licences_dentist_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='licenses',
        ),
        migrations.AddField(
            model_name='dentist',
            name='llicenses',
            field=models.FileField(blank=True, null=True, upload_to='Licenses'),
        ),
    ]
