# Generated by Django 5.1.6 on 2025-03-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0027_remove_dentist_licenses_dentist_llicenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='llicenses',
            new_name='licenses',
        ),
    ]
