# Generated by Django 5.1.6 on 2025-03-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0028_rename_llicenses_dentist_licenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='licenses',
            new_name='licence',
        ),
    ]
