# Generated by Django 5.1.6 on 2025-03-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0029_rename_licenses_dentist_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
