# Generated by Django 5.1.6 on 2025-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0030_patient_district_patient_pincode_patient_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
