# Generated by Django 5.2 on 2025-04-08 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.user')),
            ],
        ),
    ]
