# Generated by Django 5.2 on 2025-04-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0006_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.product')),
            ],
        ),
    ]
