# Generated by Django 5.2 on 2025-04-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0007_checkoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='assigned_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agrishop_app.delivery'),
        ),
    ]
