# Generated by Django 5.2 on 2025-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0008_checkout_assigned_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_verified',
            field=models.CharField(default='Not Verified', max_length=50),
        ),
    ]
