# Generated by Django 5.2 on 2025-04-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0009_checkout_delivery_status_checkout_payment_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_verified',
        ),
    ]
