# Generated by Django 5.2 on 2025-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0010_remove_checkout_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_verification',
            field=models.CharField(default='Not Verified', max_length=50),
        ),
    ]
