# Generated by Django 5.2 on 2025-04-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0013_supply_supplyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyCheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.supplycheckout')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.supply')),
            ],
        ),
    ]
