# Generated by Django 5.2 on 2025-04-10 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0014_supplycheckout_supplycheckoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycheckout',
            name='assigned_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agrishop_app.delivery'),
        ),
    ]
