# Generated by Django 5.2 on 2025-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0015_supplycheckout_assigned_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycheckout',
            name='delivery_status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
        migrations.AddField(
            model_name='supplycheckout',
            name='payment_verification',
            field=models.CharField(default='Not Verified', max_length=50),
        ),
    ]
