# Generated by Django 5.2 on 2025-04-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0016_supplycheckout_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.farmer')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.supply')),
            ],
        ),
    ]
