# Generated by Django 5.2 on 2025-04-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0017_supplyreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyReview',
        ),
    ]
