# Generated by Django 5.2 on 2025-04-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0018_delete_supplyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.supplycheckout')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.farmer')),
            ],
        ),
    ]
