# Generated by Django 5.2 on 2025-04-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0019_supplyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.user')),
            ],
        ),
    ]
