# Generated by Django 5.2 on 2025-04-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0020_favoritesupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesupply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrishop_app.farmer'),
        ),
    ]
