# Generated by Django 5.2 on 2025-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0021_alter_favoritesupply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
