# Generated by Django 5.2 on 2025-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop_app', '0022_checkout_delivery_address_checkout_delivery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycheckout',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplycheckout',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplycheckout',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='supplycheckout',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
