# Generated by Django 5.1.6 on 2025-02-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Education', 'Education'), ('Medical', 'Medical Supplies'), ('Clothing', 'Clothing'), ('General', 'General')], default='General', max_length=100)),
                ('target_amount', models.IntegerField(null=True)),
                ('current_amount', models.IntegerField(null=True)),
                ('donation_type', models.CharField(default='Monetary', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Active', max_length=50, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_donation_app.ngo')),
            ],
        ),
    ]
