# Generated by Django 5.1.6 on 2025-02-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0002_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Credit/Debit Card')], max_length=20, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_donation_app.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_donation_app.donor')),
            ],
        ),
    ]
