# Generated by Django 5.1.6 on 2025-02-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0003_donationtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_donation_app.donor')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_donation_app.ngo')),
            ],
        ),
    ]
