# Generated by Django 5.1.6 on 2025-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
