# Generated by Django 5.1.6 on 2025-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0005_alter_donation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransaction',
            name='donation_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
