# Generated by Django 5.1.6 on 2025-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_donation_app', '0006_alter_donationtransaction_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='current_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='target_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
