# Generated by Django 5.2 on 2025-04-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0002_police_department_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.police_department')),
            ],
        ),
    ]
