# Generated by Django 5.2 on 2025-04-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0003_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='Complaints/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.police_department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.user')),
            ],
        ),
    ]
