# Generated by Django 5.2 on 2025-04-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(null=True, upload_to='Reports/')),
                ('case_evidence', models.TextField()),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.complaint')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.police_department')),
            ],
        ),
    ]
