# Generated by Django 5.2 on 2025-04-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0005_casereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('last_seen_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='MissingPersons/')),
                ('status', models.CharField(default='Unresolved', max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.police_department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='casereport',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.missingperson'),
        ),
    ]
