# Generated by Django 5.2 on 2025-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0006_missingperson_casereport_missing_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
