# Generated by Django 5.2 on 2025-04-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0007_missingperson_address_missingperson_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.complaint'),
        ),
    ]
