# Generated by Django 5.2 on 2025-04-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_shield_app', '0008_alter_casereport_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='CrimeReports/')),
                ('status', models.CharField(default='Under Investigation', max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.police_department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='casereport',
            name='crime_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime_shield_app.crimereport'),
        ),
    ]
